from __future__ import annotations

import json
import logging
from dataclasses import asdict, dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


logging.basicConfig(
    level=logging.INFO,
    format="%(levelname)s %(name)s: %(message)s",
)
LOGGER = logging.getLogger("build_crawl_plan")


@dataclass(frozen=True)
class PageCategory:
    category_name: str
    priority: str
    include_patterns: list[str]
    notes: str


@dataclass(frozen=True)
class ExcludeRule:
    rule_type: str
    pattern: str
    reason: str


@dataclass(frozen=True)
class SourcePlan:
    source_name: str
    base_url: str
    priority_level: str
    page_categories: list[PageCategory]
    example_paths: list[str]
    exclude_rules: list[ExcludeRule]
    crawl_notes: list[str]


def build_ros2_plan() -> SourcePlan:
    return SourcePlan(
        source_name="ROS 2 official docs",
        base_url="https://docs.ros.org/en/jazzy/",
        priority_level="P0",
        page_categories=[
            PageCategory(
                category_name="installation_and_environment",
                priority="P0",
                include_patterns=[
                    "/Installation.html",
                    "/Installation/Alternatives/",
                    "/Tutorials/Beginner-CLI-Tools/Configuring-ROS2-Environment/",
                    "/Tutorials/Beginner-Client-Libraries/Using-Colcon-to-Build-Packages/",
                    "/Tutorials/Beginner-Client-Libraries/Creating-A-Workspace/",
                ],
                notes="Core install and workspace setup pages produce strong checklist material and prerequisite chains.",
            ),
            PageCategory(
                category_name="tutorials_and_launch",
                priority="P1",
                include_patterns=[
                    "/Tutorials/Beginner-CLI-Tools/",
                    "/Tutorials/Beginner-Client-Libraries/",
                    "/Tutorials/Intermediate/Launch/",
                    "/How-To-Guides/Using-ros2-launch-to-launch-composable-nodes.html",
                ],
                notes="Keep task-oriented tutorials that show commands, expected outputs, and launch orchestration.",
            ),
            PageCategory(
                category_name="concepts_and_architecture",
                priority="P1",
                include_patterns=[
                    "/Concepts/Basic/About-Discovery.html",
                    "/Concepts/Intermediate/About-Quality-of-Service-Settings.html",
                    "/Concepts/Intermediate/About-Executors.html",
                    "/Concepts/Intermediate/About-Composition.html",
                ],
                notes="Concept pages improve grounded Q&A and explain why procedures differ across middleware and runtime models.",
            ),
            PageCategory(
                category_name="troubleshooting_and_debugging",
                priority="P0",
                include_patterns=[
                    "/How-To-Guides/Installation-Troubleshooting.html",
                    "/Tutorials/Beginner-Client-Libraries/Getting-Started-With-Ros2doctor.html",
                    "/How-To-Guides/ROS-2-IDEs.html",
                ],
                notes="These pages are high-value for compare and checklist workflows because they include symptoms, causes, and fixes.",
            ),
            PageCategory(
                category_name="simulation_and_integration",
                priority="P2",
                include_patterns=[
                    "/Tutorials/Advanced/Simulators/",
                    "/Tutorials/Intermediate/URDF/",
                ],
                notes="Useful but lower priority than core install and debugging pages for the MVP crawl.",
            ),
        ],
        example_paths=[
            "/Installation.html",
            "/Installation/Alternatives/Ubuntu-Install-Binary.html",
            "/Tutorials/Beginner-Client-Libraries/Creating-A-Workspace/Creating-A-Workspace.html",
            "/Tutorials/Intermediate/Launch/Launch-Main.html",
            "/Concepts/Basic/About-Discovery.html",
            "/How-To-Guides/Installation-Troubleshooting.html",
            "/Tutorials/Beginner-Client-Libraries/Getting-Started-With-Ros2doctor.html",
        ],
        exclude_rules=[
            ExcludeRule("regex", r"^/en/(?!jazzy/).*", "Pin to ROS 2 Jazzy to match current ecosystem compatibility and avoid duplicate versions."),
            ExcludeRule("substring", "/_downloads/", "Skip PDFs and static downloads."),
            ExcludeRule("substring", "/Releases/", "Skip release history and archive pages."),
            ExcludeRule("substring", "/search.html", "Skip navigation/search pages."),
            ExcludeRule("substring", "/genindex.html", "Skip autogenerated indexes."),
            ExcludeRule("substring", "/py-modindex.html", "Skip autogenerated API indexes."),
            ExcludeRule("substring", "/p/", "Skip generated package API docs that are weak for workflow extraction."),
            ExcludeRule("substring", "Core-Maintainer-Guide", "Skip maintainer-only content outside MVP usage flows."),
            ExcludeRule("substring", "/Contributing/", "Skip contributor docs."),
        ],
        crawl_notes=[
            "Pinning to Jazzy is intentional: on April 22, 2026, Isaac ROS docs state packages are designed for ROS 2 Jazzy, and MoveIt getting started recommends Jazzy on Ubuntu 24.04.",
            "Preserve prerequisite blocks, ordered task lists, platform-specific tabs, admonitions, and shell commands.",
            "Treat launch, workspace, ros2doctor, QoS, discovery, and composition pages as answer-bearing reference material.",
        ],
    )


def build_px4_plan() -> SourcePlan:
    return SourcePlan(
        source_name="PX4 official docs",
        base_url="https://docs.px4.io/v1.16/en/",
        priority_level="P0",
        page_categories=[
            PageCategory(
                category_name="core_concepts_and_vehicle_setup",
                priority="P0",
                include_patterns=[
                    "/getting_started/",
                    "/assembly/",
                    "/config/",
                    "/config_mc/",
                ],
                notes="High-value setup pages contain strong procedural structure, hardware assumptions, and calibration steps.",
            ),
            PageCategory(
                category_name="developer_setup_and_simulation",
                priority="P0",
                include_patterns=[
                    "/dev_setup/",
                    "/simulation/",
                    "/sim_gazebo_gz/",
                    "/sim_sih/",
                ],
                notes="These pages are ideal for checklist extraction because they include validation commands and expected simulator behavior.",
            ),
            PageCategory(
                category_name="ros2_and_external_integration",
                priority="P0",
                include_patterns=[
                    "/ros2/",
                    "/middleware/uxrce_dds",
                    "/simulation/ros_interface",
                ],
                notes="Prioritize PX4-ROS 2 bridge setup, offboard control, and multi-system integration workflows.",
            ),
            PageCategory(
                category_name="safety_and_operational_validation",
                priority="P0",
                include_patterns=[
                    "/config/safety",
                    "/debug/failure_injection",
                    "/advanced_config/esc_calibration",
                    "/flying/",
                ],
                notes="PX4 safety material is especially valuable because it contains explicit failsafe actions, geofence logic, and emergency procedures.",
            ),
            PageCategory(
                category_name="troubleshooting",
                priority="P1",
                include_patterns=[
                    "/dev_setup/building_px4",
                    "/simulation/",
                    "/debug/",
                ],
                notes="PX4 often embeds troubleshooting inside setup pages, so keep pages that include problem-specific sections even without a separate troubleshooting index.",
            ),
        ],
        example_paths=[
            "/getting_started/px4_basic_concepts",
            "/dev_setup/building_px4",
            "/simulation/",
            "/sim_gazebo_gz/index.html",
            "/ros2/user_guide",
            "/ros2/offboard_control",
            "/middleware/uxrce_dds",
            "/config/safety.html",
        ],
        exclude_rules=[
            ExcludeRule("regex", r"^/main/.*", "Skip PX4 main docs to avoid drift against the pinned stable crawl."),
            ExcludeRule("regex", r"^/v(?!1\.16/).*", "Skip other PX4 versions to avoid duplicate content."),
            ExcludeRule("regex", r"^/v1\.16/(?!en/).*", "Skip non-English locale duplicates."),
            ExcludeRule("substring", "/release_notes/", "Skip release history."),
            ExcludeRule("substring", "/_downloads/", "Skip binary assets and downloads."),
            ExcludeRule("substring", "/contribute/", "Skip contributor workflow pages."),
            ExcludeRule("substring", "/test_and_ci/", "Skip CI-focused content for the MVP crawl."),
            ExcludeRule("substring", "/404.html", "Skip error pages."),
        ],
        crawl_notes=[
            "Pin to PX4 v1.16 English docs to stay stable while avoiding translated duplicates and main-branch drift.",
            "Preserve parameter names, QGroundControl menu paths, warning/admonition blocks, and simulator validation commands.",
            "Treat safety, failsafe, calibration, and ROS 2 bridge pages as first-class evidence sources because they are both procedure-rich and interview-friendly.",
        ],
    )


def build_moveit_plan() -> SourcePlan:
    return SourcePlan(
        source_name="MoveIt docs",
        base_url="https://moveit.picknik.ai/main/",
        priority_level="P1",
        page_categories=[
            PageCategory(
                category_name="getting_started_and_installation",
                priority="P0",
                include_patterns=[
                    "/doc/tutorials/getting_started/",
                    "/doc/how_to_guides/how_to_setup_docker_containers_in_ubuntu.html",
                ],
                notes="These pages establish the workspace, dependencies, and the most common early setup failure points.",
            ),
            PageCategory(
                category_name="tutorials_and_task_workflows",
                priority="P1",
                include_patterns=[
                    "/doc/tutorials/quickstart_in_rviz/",
                    "/doc/tutorials/your_first_project/",
                    "/doc/tutorials/pick_and_place_with_moveit_task_constructor/",
                ],
                notes="Prefer end-to-end tutorials that combine setup, launch, RViz, planning, and result inspection.",
            ),
            PageCategory(
                category_name="concepts_and_planning_models",
                priority="P1",
                include_patterns=[
                    "/doc/concepts/",
                    "/doc/concepts/motion_planning.html",
                ],
                notes="These pages support grounded explanations for planners, constraints, planning scenes, and robot models.",
            ),
            PageCategory(
                category_name="integration_and_controller_configuration",
                priority="P1",
                include_patterns=[
                    "/doc/examples/controller_configuration/",
                    "/doc/examples/moveit_cpp/",
                    "/doc/examples/planning_adapters/",
                    "/doc/how_to_guides/pick_ik/",
                    "/doc/how_to_guides/isaac_panda/",
                ],
                notes="Keep pages that explain how MoveIt connects to controllers, alternative planners, and external simulators.",
            ),
        ],
        example_paths=[
            "/doc/tutorials/getting_started/getting_started.html",
            "/doc/tutorials/quickstart_in_rviz/quickstart_in_rviz_tutorial.html",
            "/doc/tutorials/your_first_project/your_first_project.html",
            "/doc/concepts/concepts.html",
            "/doc/concepts/motion_planning.html",
            "/doc/examples/controller_configuration/controller_configuration_tutorial.html",
            "/doc/examples/moveit_cpp/moveitcpp_tutorial.html",
        ],
        exclude_rules=[
            ExcludeRule("substring", "/doc/how_to_contribute/", "Skip contribution docs."),
            ExcludeRule("substring", "/doc/how_to_guides/how_to_guide.html", "Skip the meta page about writing guides."),
            ExcludeRule("substring", "/search.html", "Skip navigation/search pages."),
            ExcludeRule("substring", "/genindex.html", "Skip autogenerated indexes."),
            ExcludeRule("substring", "/_sources/", "Skip Sphinx source artifacts."),
            ExcludeRule("substring", "MoveIt 1", "Skip links that point users out to legacy MoveIt 1 material."),
        ],
        crawl_notes=[
            "MoveIt main docs are current rolling docs, but the crawl should still focus on stable setup, tutorials, concepts, and integration pages rather than contributor material.",
            "Preserve prerequisite sections, launch commands, controller names, planner names, and warnings about missing ROS setup or memory limits.",
            "MoveIt does not have a dedicated safety section, so capture collision, constraint, and controller warnings embedded in tutorials and concepts.",
        ],
    )


def build_isaac_ros_plan() -> SourcePlan:
    return SourcePlan(
        source_name="Isaac ROS docs",
        base_url="https://nvidia-isaac-ros.github.io/",
        priority_level="P1",
        page_categories=[
            PageCategory(
                category_name="getting_started_and_system_setup",
                priority="P0",
                include_patterns=[
                    "/getting_started/",
                    "/troubleshooting/",
                ],
                notes="Core environment setup, compute requirements, dev containers, and top-level troubleshooting are the highest-value Isaac ROS pages.",
            ),
            PageCategory(
                category_name="concepts_and_acceleration",
                priority="P1",
                include_patterns=[
                    "/concepts/nitros/",
                    "/concepts/nitros_bridge/",
                ],
                notes="NITROS and bridge concepts are essential for grounded answers about Isaac ROS performance and interoperability.",
            ),
            PageCategory(
                category_name="package_quickstarts_and_tutorials",
                priority="P1",
                include_patterns=[
                    "/repositories_and_packages/isaac_ros_visual_slam/",
                    "/repositories_and_packages/isaac_ros_mapping_and_localization/",
                    "/repositories_and_packages/isaac_ros_cumotion/",
                    "/repositories_and_packages/isaac_ros_dnn_inference/",
                    "/repositories_and_packages/isaac_ros_argus_camera/",
                ],
                notes="Prioritize package pages that contain Quickstart, Tutorial, Troubleshooting, or API sections tied to concrete robotics use cases.",
            ),
            PageCategory(
                category_name="reference_workflows_and_integration",
                priority="P1",
                include_patterns=[
                    "/reference_workflows/",
                    "/concepts/nitros_bridge/tutorial_isaac_sim.html",
                ],
                notes="Reference workflows and Isaac Sim integrations are strong compare targets because they connect multiple components into a single procedure.",
            ),
        ],
        example_paths=[
            "/getting_started/index.html",
            "/troubleshooting/index.html",
            "/concepts/nitros/cuda_with_nitros.html",
            "/concepts/nitros_bridge/tutorial_isaac_sim.html",
            "/repositories_and_packages/isaac_ros_visual_slam/isaac_ros_visual_slam/index.html",
            "/repositories_and_packages/isaac_ros_cumotion/isaac_ros_cumotion/index.html",
            "/repositories_and_packages/isaac_ros_argus_camera/isaac_ros_argus_camera/index.html",
            "/reference_workflows/isaac_for_manipulation/reference_architecture.html",
        ],
        exclude_rules=[
            ExcludeRule("regex", r"^/v/.*", "Skip archived release snapshots to avoid duplicate versions."),
            ExcludeRule("regex", r"^/robots/.*", "Skip robot-kit-specific pages for the MVP crawl."),
            ExcludeRule("substring", "/_sources/", "Skip Sphinx source artifacts."),
            ExcludeRule("substring", "/search.html", "Skip navigation/search pages."),
            ExcludeRule("substring", "/genindex.html", "Skip autogenerated indexes."),
            ExcludeRule("substring", "/release_notes/", "Skip release history."),
        ],
        crawl_notes=[
            "Use the latest root docs rather than archived /v/release-* snapshots, then selectively crawl only pages with strong setup, troubleshooting, quickstart, or integration value.",
            "Preserve system requirement tables, Docker and activation commands, warnings about supported hardware, and troubleshooting subsections embedded in package pages.",
            "Isaac ROS has limited explicit safety material, so prioritize operational guardrails such as supported platform constraints, sensor setup caveats, and troubleshooting warnings.",
        ],
    )


def global_exclude_rules() -> list[dict[str, str]]:
    rules = [
        ExcludeRule("substring", "/search", "Skip search and navigation endpoints."),
        ExcludeRule("substring", "/genindex", "Skip autogenerated indexes."),
        ExcludeRule("substring", "/_downloads/", "Skip PDFs and binary assets."),
        ExcludeRule("substring", "/_sources/", "Skip source artifacts."),
        ExcludeRule("substring", "release_notes", "Skip release archives and changelogs."),
        ExcludeRule("substring", "how_to_contribute", "Skip authoring and contributor pages."),
    ]
    return [asdict(rule) for rule in rules]


def build_crawl_plan() -> dict[str, Any]:
    sources = [
        build_ros2_plan(),
        build_px4_plan(),
        build_moveit_plan(),
        build_isaac_ros_plan(),
    ]

    priority_order = {"P0": 0, "P1": 1, "P2": 2}
    sources.sort(key=lambda plan: (priority_order.get(plan.priority_level, 99), plan.source_name))

    return {
        "plan_name": "high_value_engineering_docs_mvp",
        "project_name": "Grounded Engineering Document Workflow Agent",
        "generated_at_utc": datetime.now(timezone.utc).isoformat().replace("+00:00", "Z"),
        "selection_objective": [
            "evidence-backed Q&A",
            "document and procedure comparison",
            "checklist extraction",
        ],
        "global_include_focus": [
            "installation",
            "setup",
            "tutorials",
            "concepts",
            "troubleshooting",
            "integration",
            "safety",
        ],
        "global_exclude_rules": global_exclude_rules(),
        "sources": [asdict(source) for source in sources],
    }


def write_crawl_plan(output_path: Path) -> Path:
    plan = build_crawl_plan()
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(
        json.dumps(plan, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
    LOGGER.info("Wrote crawl plan to %s", output_path)
    return output_path


def main() -> None:
    project_root = Path(__file__).resolve().parents[1]
    output_path = project_root / "data" / "crawl_plan.json"
    write_crawl_plan(output_path)


if __name__ == "__main__":
    main()
